# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!
#use_modular_headers!
inhibit_all_warnings!

#指定workspace 名称
workspace 'NvShortVideo.xcworkspace'

target 'NvShortVideo' do
  project 'NvShortVideo.xcodeproj'
  
  # NvShortVideoCore
  pod 'NvShortVideoEdit',    :path => '../'

end



post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end

