var hierarchy =
[
    [ "com.meishe.config.NvBubbleConfig.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1_nv_bubble_config_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvAlbumCellTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_album_cell_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvCaptionViewTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_caption_view_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvEffectTimeRangeViewTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_effect_time_range_view_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvEffectTrackViewTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_effect_track_view_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvMaterialCellTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_material_cell_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvMusciCutViewTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_musci_cut_view_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvMusicCellTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_music_cell_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.custom.NvMusicSearchCellTheme.ConfigViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_music_search_cell_theme_1_1_config_view_holder.html", null ],
    [ "com.meishe.config.theme.theme_element.NvViewTheme.Holder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_view_theme_1_1_holder.html", null ],
    [ "com.meishe.config.NvBeautyConfig.NvBeautyAdjust", "enumcom_1_1meishe_1_1config_1_1_nv_beauty_config_1_1_nv_beauty_adjust.html", null ],
    [ "com.meishe.config.NvBeautyConfig.NvBeautyCategorical", "enumcom_1_1meishe_1_1config_1_1_nv_beauty_config_1_1_nv_beauty_categorical.html", null ],
    [ "com.meishe.config.NvBeautyConfig.NvBeautyEffect", "enumcom_1_1meishe_1_1config_1_1_nv_beauty_config_1_1_nv_beauty_effect.html", null ],
    [ "com.meishe.config.NvBeautyConfig.NvBeautyMicroShape", "enumcom_1_1meishe_1_1config_1_1_nv_beauty_config_1_1_nv_beauty_micro_shape.html", null ],
    [ "com.meishe.config.NvBeautyConfig.NvBeautyShape", "enumcom_1_1meishe_1_1config_1_1_nv_beauty_config_1_1_nv_beauty_shape.html", null ],
    [ "com.meishe.config.NvBubbleConfig.NvBubbleBgBlurStyle", "enumcom_1_1meishe_1_1config_1_1_nv_bubble_config_1_1_nv_bubble_bg_blur_style.html", null ],
    [ "com.meishe.config.NvCaptureConfig.NvCaptureBottomMenuItem", "enumcom_1_1meishe_1_1config_1_1_nv_capture_config_1_1_nv_capture_bottom_menu_item.html", null ],
    [ "com.meishe.config.NvCaptureConfig.NvCaptureMenuItem", "enumcom_1_1meishe_1_1config_1_1_nv_capture_config_1_1_nv_capture_menu_item.html", null ],
    [ "com.meishe.config.NvDualConfig.NvDualType", "enumcom_1_1meishe_1_1config_1_1_nv_dual_config_1_1_nv_dual_type.html", null ],
    [ "com.meishe.config.NvEditConfig.NvEditMenuItem", "enumcom_1_1meishe_1_1config_1_1_nv_edit_config_1_1_nv_edit_menu_item.html", null ],
    [ "com.meishe.config.NvEditConfig.NvEditMode", "enumcom_1_1meishe_1_1config_1_1_nv_edit_config_1_1_nv_edit_mode.html", null ],
    [ "com.meishe.config.NvEditConfig.NvEditModeSource", "enumcom_1_1meishe_1_1config_1_1_nv_edit_config_1_1_nv_edit_mode_source.html", null ],
    [ "com.meishe.config.NvCompileConfig.NvExportImageType", "enumcom_1_1meishe_1_1config_1_1_nv_compile_config_1_1_nv_export_image_type.html", null ],
    [ "com.meishe.config.NvEditConfig.NvImageCaptionStyle", "enumcom_1_1meishe_1_1config_1_1_nv_edit_config_1_1_nv_image_caption_style.html", null ],
    [ "com.meishe.config.NvCompileConfig.NvsCompileVideoBitrateGrade", "enumcom_1_1meishe_1_1config_1_1_nv_compile_config_1_1_nvs_compile_video_bitrate_grade.html", null ],
    [ "com.meishe.config.NvCompileConfig.NvVideoCompileResolution", "enumcom_1_1meishe_1_1config_1_1_nv_compile_config_1_1_nv_video_compile_resolution.html", null ],
    [ "com.meishe.config.NvCompileConfig.NvVideoPreviewResolution", "enumcom_1_1meishe_1_1config_1_1_nv_compile_config_1_1_nv_video_preview_resolution.html", null ],
    [ "com.meishe.config.theme.custom.NvVideoTrackEditViewTheme.ViewHolder", "interfacecom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_video_track_edit_view_theme_1_1_view_holder.html", null ],
    [ "Serializable", null, [
      [ "com.meishe.config.BaseConfig", "classcom_1_1meishe_1_1config_1_1_base_config.html", [
        [ "com.meishe.config.NvAlbumConfig", "classcom_1_1meishe_1_1config_1_1_nv_album_config.html", null ],
        [ "com.meishe.config.NvCaptureConfig", "classcom_1_1meishe_1_1config_1_1_nv_capture_config.html", null ],
        [ "com.meishe.config.NvCompileConfig", "classcom_1_1meishe_1_1config_1_1_nv_compile_config.html", null ],
        [ "com.meishe.config.NvEditConfig", "classcom_1_1meishe_1_1config_1_1_nv_edit_config.html", null ],
        [ "com.meishe.config.NvImageConfig", "classcom_1_1meishe_1_1config_1_1_nv_image_config.html", null ],
        [ "com.meishe.config.NvModelConfig", "classcom_1_1meishe_1_1config_1_1_nv_model_config.html", null ],
        [ "com.meishe.config.NvTemplateConfig", "classcom_1_1meishe_1_1config_1_1_nv_template_config.html", null ],
        [ "com.meishe.config.NvVideoConfig", "classcom_1_1meishe_1_1config_1_1_nv_video_config.html", null ],
        [ "com.meishe.config.NvWatermarkConfig", "classcom_1_1meishe_1_1config_1_1_nv_watermark_config.html", null ]
      ] ],
      [ "com.meishe.config.NvAlbumConfig", "classcom_1_1meishe_1_1config_1_1_nv_album_config.html", null ],
      [ "com.meishe.config.NvBeautyConfig", "classcom_1_1meishe_1_1config_1_1_nv_beauty_config.html", null ],
      [ "com.meishe.config.NvBubbleConfig", "classcom_1_1meishe_1_1config_1_1_nv_bubble_config.html", null ],
      [ "com.meishe.config.NvCaptureConfig", "classcom_1_1meishe_1_1config_1_1_nv_capture_config.html", null ],
      [ "com.meishe.config.NvCompileConfig", "classcom_1_1meishe_1_1config_1_1_nv_compile_config.html", null ],
      [ "com.meishe.config.NvDualConfig", "classcom_1_1meishe_1_1config_1_1_nv_dual_config.html", null ],
      [ "com.meishe.config.NvEditConfig", "classcom_1_1meishe_1_1config_1_1_nv_edit_config.html", null ],
      [ "com.meishe.config.NvImageConfig", "classcom_1_1meishe_1_1config_1_1_nv_image_config.html", null ],
      [ "com.meishe.config.NvModelConfig", "classcom_1_1meishe_1_1config_1_1_nv_model_config.html", null ],
      [ "com.meishe.config.NvShadowOffsetConfig", "classcom_1_1meishe_1_1config_1_1_nv_shadow_offset_config.html", null ],
      [ "com.meishe.config.NvTemplateConfig", "classcom_1_1meishe_1_1config_1_1_nv_template_config.html", null ],
      [ "com.meishe.config.NvTimePair", "classcom_1_1meishe_1_1config_1_1_nv_time_pair.html", null ],
      [ "com.meishe.config.NvVideoConfig", "classcom_1_1meishe_1_1config_1_1_nv_video_config.html", null ],
      [ "com.meishe.config.NvWatermarkConfig", "classcom_1_1meishe_1_1config_1_1_nv_watermark_config.html", null ],
      [ "com.meishe.config.theme.theme_element.NvViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_view_theme.html", [
        [ "com.meishe.config.theme.custom.NvBeautyPanelTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_beauty_panel_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvCaptionViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_caption_view_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvEffectTimeRangeViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_effect_time_range_view_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvEffectTrackViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_effect_track_view_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvMusciCutViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_musci_cut_view_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvRecordBtTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_record_bt_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvTemplateEditClipSectionTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_template_edit_clip_section_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvTemplateHomeDataErrorTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_template_home_data_error_theme.html", null ],
        [ "com.meishe.config.theme.custom.NvVideoTrackEditViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_video_track_edit_view_theme.html", null ],
        [ "com.meishe.config.theme.theme_element.NvButtonTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_button_theme.html", null ],
        [ "com.meishe.config.theme.theme_element.NvCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_cell_theme.html", [
          [ "com.meishe.config.theme.custom.NvAlbumCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_album_cell_theme.html", null ],
          [ "com.meishe.config.theme.custom.NvMaterialCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_material_cell_theme.html", null ],
          [ "com.meishe.config.theme.custom.NvMusicCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_music_cell_theme.html", null ],
          [ "com.meishe.config.theme.custom.NvMusicSearchCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_music_search_cell_theme.html", null ],
          [ "com.meishe.config.theme.custom.NvRecognitionEditCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_recognition_edit_cell_theme.html", null ],
          [ "com.meishe.config.theme.custom.NvTemplateHomeCellTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1custom_1_1_nv_template_home_cell_theme.html", null ]
        ] ],
        [ "com.meishe.config.theme.theme_element.NvImageViewTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_image_view_theme.html", null ],
        [ "com.meishe.config.theme.theme_element.NvLabelTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_label_theme.html", [
          [ "com.meishe.config.theme.theme_element.NvTextFieldTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_text_field_theme.html", null ]
        ] ],
        [ "com.meishe.config.theme.theme_element.NvSliderTheme", "classcom_1_1meishe_1_1config_1_1theme_1_1theme__element_1_1_nv_slider_theme.html", null ]
      ] ]
    ] ]
];